In [2]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
a = [1,2,3,'5']
b = np.array(a , dtype = int)
print(b)

[1 2 3 5]


In [11]:
a = [1,2,3,'5']
b = np.array(a *3)
print(b)

['1' '2' '3' '5' '1' '2' '3' '5' '1' '2' '3' '5']


In [14]:
b = np.ones(3 , dtype =int)
b

array([1, 1, 1])

In [17]:
b = np.ones((3,4) , dtype =int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [16]:
b = np.zeros(3 , dtype =int)
b

array([0, 0, 0])

In [18]:
b = np.zeros((4,3) , dtype =int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
b = np.full(3,4)
b

array([4, 4, 4])

In [21]:
b = np.full((3,4),5)
b

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [34]:
#numpy.empty(shape, dtype = float, order = ‘C’) : Return a new array of given shape and type, with random values.

c = np.empty(5, dtype = int)
c

array([0, 0, 0, 0, 0])

In [48]:
c = np.empty((3,3), dtype = int)
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [51]:
#NumPy 2D array

import numpy as np

d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

n = np.array(d)
print(n)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
import numpy as np

b = np.zeros(10,dtype = int)
b[5] = 1

for x in range(len(b)):
    print(b[x],end=" ")

0 0 0 0 0 1 0 0 0 0 

In [9]:
# araneg

b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [13]:
b = np.arange(2,20,3)
b

array([ 2,  5,  8, 11, 14, 17])

In [21]:
#linspace

b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [23]:
b = np.linspace(2,10,5,dtype=int)
b

array([ 2,  4,  6,  8, 10])

In [29]:
b = np.linspace(2,10,5,dtype= float, retstep = True)
b

(array([ 2.,  4.,  6.,  8., 10.]), 2.0)

In [30]:
b = np.linspace(2,10,5,dtype= float, endpoint=False)
b

array([2. , 3.6, 5.2, 6.8, 8.4])

In [31]:
# identity

b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
#eye

b = np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
b = np.eye(2,3)
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [34]:
#random.rand

b = np.random.rand(3)
b

array([0.16875733, 0.25387509, 0.69581273])

In [43]:
b = np.random.rand(10)*10
b

array([9.34431939, 4.30534358, 1.12897698, 4.04189834, 9.82427766,
       1.52823209, 4.54086417, 1.02360445, 6.01009958, 8.13310001])

In [35]:
b = np.random.rand(2,3)
b

array([[0.78235533, 0.96054197, 0.6438785 ],
       [0.37066721, 0.40034763, 0.47303797]])

In [47]:
b = np.random.randint(2, size=10)
b

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0])

In [48]:
b = np.random.randint(1, size=10)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
b = np.random.randint(5, size=(2,3))
b

array([[0, 3, 1],
       [4, 2, 1]])

In [3]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [5]:
a = np.random.rand()
a

0.9244033947432231

In [10]:
a =np.random.randint(10, 4)
a

ValueError: low >= high

In [56]:
#NumPy Inclusive

import numpy as np

a = np.arange(9,50)
a

for x in range(len(a)):
    print(a[x],end=" ")

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

In [18]:
#Identity Matrix

import numpy as np

a = np.eye(5,6,dtype=int)
print(a)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [26]:
#Cut the Rope


import numpy as np

a=np.linspace(0,5,10)[1:9]
a=list(a)

for i in a:
    i=round(i,2)
    print(i)

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


# Slicing & Indexing

In [31]:
#1d array
import numpy as np

li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [33]:
print(li[1])
print(arr[1])

print(li[1:4])
print(arr[1:4])

2
2
[2, 3, 4]
[2 3 4]


In [21]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [36]:
#2d array

#1d array
import numpy as np

li_2d = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 5)
int32
(20, 4)


In [44]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

12
12
12


In [45]:
print(arr_2d[2:4,1:4])

[[12 13 14]
 [17 18 19]]


In [46]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [81]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

x = input_[2:3,0:3]
for i in range(len(x)):
    print(*x[i],end=" ")

y = input_[1:4,3:4]
for i in range(len(y)):
    print(*y[i],end=" ")
    
z = input_[2:4]
for i in range(len(z)):
    print(*z[i],end=" ")
    
w = input_[1:3,1:3]
for i in range(len(w)):
    print(*w[i],end=" ")

11 12 13 9 14 19 11 12 13 14 15 16 17 18 19 20 7 8 12 13 

In [75]:
x = input_[2:3,0:3]
for i in range(len(x)):
    print(*x[i],end=" ")

11 12 13 

In [76]:
y = input_[1:4,3:4]
for i in range(len(y)):
    print(*y[i],end=" ")

9 14 19 

In [79]:
z = input_[2:4]
for i in range(len(z)):
    print(*z[i],end=" ")

11 12 13 14 15 16 17 18 19 20 

In [80]:
z = input_[1:3,1:3]
for i in range(len(z)):
    print(*z[i],end=" ")

7 8 12 13 

In [82]:
#Print Elements

import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

x = input_[2:3,0:3]
for i in range(len(x)):
    print(*x[i],end=" ")

print()
    
y = input_[1:4,3:4]
for i in range(len(y)):
    print(*y[i],end=" ")
    
print()

z = input_[2:4]
for i in range(len(z)):
    print(*z[i],end=" ")
    
print()

w = input_[1:3,1:3]
for i in range(len(w)):
    print(*w[i],end=" ")

11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

# Mathematical Operations - 1D

In [84]:
import numpy as np

li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 2 14 12  2  6]
[17  3 11  7  3]


In [86]:
li = [i+1 for i in li]
li

[3, 4, 5, 6, 7]

In [88]:
a = a+1
a

array([ 4, 16, 14,  4,  8])

In [90]:
c = a+b
c

array([21, 19, 25, 11, 11])

In [92]:
d = a-b
d

array([-13,  13,   3,  -3,   5])

In [93]:
e = a / b
e

array([0.23529412, 5.33333333, 1.27272727, 0.57142857, 2.66666667])

In [94]:
f = a *b
f

array([ 68,  48, 154,  28,  24])

In [95]:
g = a // b
g

array([0, 5, 1, 0, 2], dtype=int32)

In [96]:
h = a**b
h

array([         0,       4096, -588990464,      16384,        512],
      dtype=int32)

In [103]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 4 16 14  4  8]
46
9.2
4
0
16
1


In [104]:
a > b

array([False,  True,  True, False,  True])

In [105]:
a < b

array([ True, False, False,  True, False])

In [106]:
a == b

array([False, False, False, False, False])

In [110]:
print(a)
print(b)

[ 4 16 14  4  8]
[17  3 11  7  3]


In [108]:
print(np.logical_or(a,b))

[ True  True  True  True  True]


In [109]:
print(np.logical_and(a,b))

[ True  True  True  True  True]


In [111]:
print(np.logical_not(a))

[False False False False False]


In [112]:
a[2] = 0
print(np.logical_not(a))

[False False  True False False]


# Boolean Indexing - 1D

In [114]:
import numpy as np

a = np.array(["t","b","r","d","e","f","z","a"])
b = np.random.randint(1,20,8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 8  8 15  5  3 14  9  3]


In [116]:
print(b>10)

[False False  True False False  True False False]


In [117]:
bool_array = b > 10
print(bool_array)
new_array = b[bool_array]
print(new_array)

[False False  True False False  True False False]
[15 14]


In [118]:
new = b[b>10]
new

array([15, 14])

In [119]:
new_array =  b[(b >5) & (b<20)] 
new_array

array([ 8,  8, 15, 14,  9])

In [122]:
print(b)
c = b
c

[ 8  8 15  5  3 14  9  3]


array([ 8,  8, 15,  5,  3, 14,  9,  3])

In [127]:
c[:3] = 19
print(c)

[19 19 19  5  3 14  9  3]


In [133]:
c[c > 15] = 40
c

array([40, 40, 40,  5,  3, 14,  9,  3])

In [135]:
ind = np.where(c == 40)
ind

(array([0, 1, 2], dtype=int64),)

In [63]:
print(a)
print(b)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


NameError: name 'b' is not defined

In [42]:
ind = np.where(b == 40)
print(ind)
print(a[ind])

NameError: name 'b' is not defined

In [9]:
#Non-Zero elements

import numpy as np

a = np.array([1,2,0,0,4,0])

ind1 = np.where(a != 0)

for i in ind1:
    print(*i,end= " ")

0 1 4 

In [15]:
#Multiples of 3

import numpy as np

a = np.array([1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

ind1 = np.where(a % 2 == 0)

for i in ind1:
    print(*i,end= " ")



1 4 7 

In [22]:
#Odd elements

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

ind1 = np.where(a % 2 == 1)

for i in ind1:
    a[i] = -1
    print(*a)

-1 2 -1 4 -1 6 -1 8 -1 10


In [33]:
#Replace Max

import numpy as np

a = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])

a1 = a.argmax()

a[a1]= 0

for i in a:
    print(i)

11
2
13
4
15
6
0
8
19


In [39]:
#Negate Elements

import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

a[2:8] = np.multiply(a[2:8],-1)

for i in a:
    print(i)


1
2
-3
-4
-5
-6
-7
-8
9
10


In [69]:
#Height

## Print the required output in given format
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

#ind = np.where(height > 155)

for i in range(20):
    if height[i]>155:
        print(age[i],height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


# Boolean Indexing - 2D

In [71]:
import numpy as np

a = np.random.randint(1,30,(5,6))
print(a)

[[11 13  8 16  4 27]
 [18 18 16 15 19  7]
 [18 14 16 13  9 13]
 [13 26 16  9  5 25]
 [26  2  8 21 20 11]]


In [74]:
bool_arr = a > 20
print(bool_arr)

[[False False False False False  True]
 [False False False False False False]
 [False False False False False False]
 [False  True False False False  True]
 [ True False False  True False False]]


In [75]:
ans = a[bool_arr]
print(ans)

[27 26 25 26 21]


In [81]:
b = a
print(b)

[[ 11  13   8  16   4  99]
 [ 18  18  16  15  19  99]
 [ 18  14  16  13   9  99]
 [ 13 100  16   9   5  99]
 [100   2   8 100  20  99]]


In [82]:
b[bool_arr] = 100
print(b)

IndexError: index 99 is out of bounds for axis 0 with size 5

In [79]:
bool_arr = b[:,5] = 99
print(bool_arr)

99


In [90]:
import numpy as np

arr2D = np.array ([[21,20, 19, 18, 17],[16, 15, 14, 13, 12],[11, 10,  9,  8,  7],[ 6,  5,  4,  3,  2]])

# Sort 2D numpy array by 2nd Column
sortedArr = arr2D[arr2D[:,1].argsort()]
 
print(sortedArr)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [7]:
import numpy as np
import csv
file_obj=open("terrorismData.csv",encoding="utf8")
file_data=csv.DictReader(file_obj,skipinitialspace=True)
country=[]
killed=[]
wounded=[]
city=[]
final=[]

#Making lists
for row in file_data:
    if row['Country']=='India':
        country.append(row['Country'])
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        city.append(row['City'])
        final.append([row['City'],row['Killed'],row['Wounded']])

#Making numpy arrays out of lists
np_month=np.array(country)
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_city=np.array(city)
np_final=np.array(final)

#Fixing blank values in final arr
for i in range(len(np_final)):
    for j in range(len(np_final[0])):
        if np_final[i][j]=='':
            np_final[i][j]='0.0'

#Counting casualities(killed+wounded) and storing in 1st column of final array
for i in range(len(np_final)):
    np_final[i,1]=float(np_final[i,1])+float(np_final[i,2])

#Descending sort on casualities column
np_final=np_final[np_final[:,1].argsort()[::-1]]


In [ ]:
#Killed in USA
import numpy as np
import csv

reader = csv.DictReader(open('terrorismData.csv'), skipinitialspace=True)
l = list(reader)

usl = []
killed = []
i = 0 
for row in l:
    if row['Country'] != '' and row['Country'] == 'United States':
        if row['Killed'] == '':
            print(0)
        else:
            print(int(float(row['Killed'])))
            i+=int(float(row['Killed']))

# Assignment

In [1]:
import numpy as np
import csv

reader = csv.DictReader(open('terrorismData.csv',encoding="utf8"),skipinitialspace=True)
l = list(reader)

cnt = 0
for row in l:
    if row['Day'] is not None and row['Day'] != '' and int(row['Day']) >= 10 and int(row['Day']) <=20:
        cnt+=1
print(cnt)

66330


In [3]:
#Terrorism Date

import numpy as np
import csv

day = []
with open('terrorismData.csv',encoding='ISO-8859-1') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Year'] is not None and row['Year'] != '' and int(row['Year']) == 2010:
            if row['Month'] is not None and row['Month'] != '' and int(row['Month']) ==1:
                if row['Day'] is not None and row['Day'] != '' and int(row['Day']) >=1 and int(row['Day']) <= 31:
                    day.append(row)
    print(np.count_nonzero(day))

271


In [ ]:
#Terror City Casualty

import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace=True)
   
    city = []
    killed = []
    wounded = []
   
    for row in file_data:
        if row['Country'] == 'India' and row['City'] != 'Unknown':
            city.append(row['City'])
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
          
    np_city   = np.array(city)
    np_killed  = np.array(killed)
    np_wounded = np.array(wounded)   
    
    np_killed[np_killed == ''] = '0.0'
    np_wounded[np_wounded == ''] = '0.0'
       
    np_killed  = np.array(np_killed,dtype=float)
    np_killed  = np.array(np_killed,dtype=int)
    np_wounded = np.array(np_wounded,dtype=float)
    np_wounded = np.array(np_wounded,dtype=int)
    np_casualty = np_killed + np_wounded
    
    np_city_u   = np.unique(np_city)
    cas_u    = []
    for ind_city in np_city_u:
        tot_cas = np.sum(np_casualty[(np_city == ind_city)])
        cas_u.append(tot_cas)
    np_cas_u    = np.array(cas_u)
    ind = np_cas_u.argsort()
    ind = ind[::-1]
    ind = ind[:5]
    for i in ind:
        print(np_city_u[i],np_cas_u[i])

In [4]:
#Terror Casualty Red

import numpy as np
import csv
with open('terrorismData.csv',encoding="utf8") as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace=True)
   
    state = []
    killed = []
    wounded = []
   
    for row in file_data:
        if row['Country'] == 'India':
            state.append(row['State'])
            killed.append(row['Killed'])
            wounded.append(row['Wounded'])
          
    np_state   = np.array(state)
    np_killed  = np.array(killed)
    np_wounded = np.array(wounded)   
    
    np_killed[np_killed == ''] = '0.0'
    np_wounded[np_wounded == ''] = '0.0'
       
    np_killed  = np.array(np_killed,dtype=float)
    np_killed  = np.array(np_killed,dtype=int)
    np_wounded = np.array(np_wounded,dtype=float)
    np_wounded = np.array(np_wounded,dtype=int)
    np_casualty = np_killed + np_wounded
    
    bool_red = (np_state == 'Jharkhand') | (np_state == 'Odisha') | (np_state == 'Andhra Pradesh') | (np_state == 'Chhattisgarh')
   
    np_cas_filter  = np_casualty[(bool_red)]
    cas_count = np.sum(np_cas_filter)
    print(cas_count)

5628
